jjwt:
  expiration: ${JWT_EXPIRATION:1800}
  secret: ${JWT_SECRET:change-me-change-me-change-me-change-me}

spring:
  mongodb:
    uri: mongodb://localhost:27017/meseroapp
  main:
    web-application-type: reactive
  threads:
    virtual:
      enabled: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

